version: "3"

services:
    database:
        image: mongo
        logging:
            driver: none
        ports:
            - 27017:27017
        volumes:
            - ./data:/data/db
        container_name: database-test

    backend:
        image: backend-test
        build:
            context: .
            dockerfile: Dockerfile
            target: test
        volumes:
            - .:/usr/src/app
        environment:
            - NODE_ENV=test
            - PORT=3001
            - MONGODB_URI=mongodb://database/testdb:27017
        ports:
            - 3001:3001
        depends_on:
            - database
        container_name: backend-test
