version: "3"

services:
    backend:
        image: backend-development
        build:
            context: .
            dockerfile: dev.Dockerfile
        volumes:
            - .:/usr/src/app
        environment:
            - NODE_ENV=development
            - PORT=3001
        ports:
            - 3001:3001
        container_name: backend-development
